// SPDX-License-Identifier: MIT
// apps/backend/src/config/rbac.ts

/**
 * RBAC Configuration
 *
 * Defines default roles and their permissions for the ERP system.
 * This configuration can be overridden in the database.
 *
 * @module config/rbac
 */

import {
  RoleNames,
  ModuleNames,
  PermissionActions,
  type RoleDefinition,
  type RoleHierarchy,
  type Permission,
} from "../types/rbac.js";

/**
 * Permission builder helper
 */
function buildPermission(
  module: ModuleNames | string,
  action: PermissionActions | string,
): Permission {
  return `${module}:${action}` as Permission;
}

/**
 * Module permission builders
 */
const ModulePermissions = {
  dashboard: {
    read: buildPermission(ModuleNames.DASHBOARD, PermissionActions.READ),
    export: buildPermission(ModuleNames.DASHBOARD, PermissionActions.EXPORT),
  },
  userManagement: {
    create: buildPermission(
      ModuleNames.USER_MANAGEMENT,
      PermissionActions.CREATE,
    ),
    read: buildPermission(ModuleNames.USER_MANAGEMENT, PermissionActions.READ),
    update: buildPermission(
      ModuleNames.USER_MANAGEMENT,
      PermissionActions.UPDATE,
    ),
    delete: buildPermission(
      ModuleNames.USER_MANAGEMENT,
      PermissionActions.DELETE,
    ),
    manage: buildPermission(
      ModuleNames.USER_MANAGEMENT,
      PermissionActions.MANAGE,
    ),
  },
  roleManagement: {
    create: buildPermission(
      ModuleNames.ROLE_MANAGEMENT,
      PermissionActions.CREATE,
    ),
    read: buildPermission(ModuleNames.ROLE_MANAGEMENT, PermissionActions.READ),
    update: buildPermission(
      ModuleNames.ROLE_MANAGEMENT,
      PermissionActions.UPDATE,
    ),
    delete: buildPermission(
      ModuleNames.ROLE_MANAGEMENT,
      PermissionActions.DELETE,
    ),
    manage: buildPermission(
      ModuleNames.ROLE_MANAGEMENT,
      PermissionActions.MANAGE,
    ),
  },
  finance: {
    create: buildPermission(ModuleNames.FINANCE, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.FINANCE, PermissionActions.READ),
    update: buildPermission(ModuleNames.FINANCE, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.FINANCE, PermissionActions.DELETE),
    approve: buildPermission(ModuleNames.FINANCE, PermissionActions.APPROVE),
    export: buildPermission(ModuleNames.FINANCE, PermissionActions.EXPORT),
  },
  hr: {
    create: buildPermission(ModuleNames.HR, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.HR, PermissionActions.READ),
    update: buildPermission(ModuleNames.HR, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.HR, PermissionActions.DELETE),
    approve: buildPermission(ModuleNames.HR, PermissionActions.APPROVE),
    export: buildPermission(ModuleNames.HR, PermissionActions.EXPORT),
  },
  crm: {
    create: buildPermission(ModuleNames.CRM, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.CRM, PermissionActions.READ),
    update: buildPermission(ModuleNames.CRM, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.CRM, PermissionActions.DELETE),
    export: buildPermission(ModuleNames.CRM, PermissionActions.EXPORT),
  },
  sales: {
    create: buildPermission(ModuleNames.SALES, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.SALES, PermissionActions.READ),
    update: buildPermission(ModuleNames.SALES, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.SALES, PermissionActions.DELETE),
    approve: buildPermission(ModuleNames.SALES, PermissionActions.APPROVE),
    export: buildPermission(ModuleNames.SALES, PermissionActions.EXPORT),
  },
  procurement: {
    create: buildPermission(ModuleNames.PROCUREMENT, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.PROCUREMENT, PermissionActions.READ),
    update: buildPermission(ModuleNames.PROCUREMENT, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.PROCUREMENT, PermissionActions.DELETE),
    approve: buildPermission(
      ModuleNames.PROCUREMENT,
      PermissionActions.APPROVE,
    ),
    export: buildPermission(ModuleNames.PROCUREMENT, PermissionActions.EXPORT),
  },
  inventory: {
    create: buildPermission(ModuleNames.INVENTORY, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.INVENTORY, PermissionActions.READ),
    update: buildPermission(ModuleNames.INVENTORY, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.INVENTORY, PermissionActions.DELETE),
    export: buildPermission(ModuleNames.INVENTORY, PermissionActions.EXPORT),
  },
  production: {
    create: buildPermission(ModuleNames.PRODUCTION, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.PRODUCTION, PermissionActions.READ),
    update: buildPermission(ModuleNames.PRODUCTION, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.PRODUCTION, PermissionActions.DELETE),
    approve: buildPermission(ModuleNames.PRODUCTION, PermissionActions.APPROVE),
    export: buildPermission(ModuleNames.PRODUCTION, PermissionActions.EXPORT),
  },
  warehouse: {
    create: buildPermission(ModuleNames.WAREHOUSE, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.WAREHOUSE, PermissionActions.READ),
    update: buildPermission(ModuleNames.WAREHOUSE, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.WAREHOUSE, PermissionActions.DELETE),
    export: buildPermission(ModuleNames.WAREHOUSE, PermissionActions.EXPORT),
  },
  settings: {
    read: buildPermission(ModuleNames.SETTINGS, PermissionActions.READ),
    update: buildPermission(ModuleNames.SETTINGS, PermissionActions.UPDATE),
    configure: buildPermission(
      ModuleNames.SETTINGS,
      PermissionActions.CONFIGURE,
    ),
  },
  monitoring: {
    read: buildPermission(ModuleNames.MONITORING, PermissionActions.READ),
    configure: buildPermission(
      ModuleNames.MONITORING,
      PermissionActions.CONFIGURE,
    ),
  },
  auditLogs: {
    read: buildPermission(ModuleNames.AUDIT_LOGS, PermissionActions.READ),
    export: buildPermission(ModuleNames.AUDIT_LOGS, PermissionActions.EXPORT),
  },
  aiAnnotator: {
    create: buildPermission(ModuleNames.AI_ANNOTATOR, PermissionActions.CREATE),
    read: buildPermission(ModuleNames.AI_ANNOTATOR, PermissionActions.READ),
    update: buildPermission(ModuleNames.AI_ANNOTATOR, PermissionActions.UPDATE),
    delete: buildPermission(ModuleNames.AI_ANNOTATOR, PermissionActions.DELETE),
    configure: buildPermission(
      ModuleNames.AI_ANNOTATOR,
      PermissionActions.CONFIGURE,
    ),
  },
  reporting: {
    read: buildPermission(ModuleNames.REPORTING, PermissionActions.READ),
    create: buildPermission(ModuleNames.REPORTING, PermissionActions.CREATE),
    export: buildPermission(ModuleNames.REPORTING, PermissionActions.EXPORT),
  },
};

/**
 * Default RBAC Roles
 */
export const DEFAULT_ROLES: RoleDefinition[] = [
  {
    id: "role_super_admin",
    name: RoleNames.SUPER_ADMIN,
    display_name: "Super Administrator",
    description:
      "Full system access. Can manage all users, roles, and configurations.",
    is_system: true,
    is_active: true,
    permissions: [
      // All permissions
      ModulePermissions.userManagement.manage,
      ModulePermissions.roleManagement.manage,
      ModulePermissions.dashboard.read,
      ModulePermissions.dashboard.export,
      ModulePermissions.finance.create,
      ModulePermissions.finance.read,
      ModulePermissions.finance.update,
      ModulePermissions.finance.delete,
      ModulePermissions.finance.approve,
      ModulePermissions.finance.export,
      ModulePermissions.hr.create,
      ModulePermissions.hr.read,
      ModulePermissions.hr.update,
      ModulePermissions.hr.delete,
      ModulePermissions.hr.approve,
      ModulePermissions.hr.export,
      ModulePermissions.crm.create,
      ModulePermissions.crm.read,
      ModulePermissions.crm.update,
      ModulePermissions.crm.delete,
      ModulePermissions.crm.export,
      ModulePermissions.sales.create,
      ModulePermissions.sales.read,
      ModulePermissions.sales.update,
      ModulePermissions.sales.delete,
      ModulePermissions.sales.approve,
      ModulePermissions.sales.export,
      ModulePermissions.procurement.create,
      ModulePermissions.procurement.read,
      ModulePermissions.procurement.update,
      ModulePermissions.procurement.delete,
      ModulePermissions.procurement.approve,
      ModulePermissions.procurement.export,
      ModulePermissions.inventory.create,
      ModulePermissions.inventory.read,
      ModulePermissions.inventory.update,
      ModulePermissions.inventory.delete,
      ModulePermissions.inventory.export,
      ModulePermissions.production.create,
      ModulePermissions.production.read,
      ModulePermissions.production.update,
      ModulePermissions.production.delete,
      ModulePermissions.production.approve,
      ModulePermissions.production.export,
      ModulePermissions.warehouse.create,
      ModulePermissions.warehouse.read,
      ModulePermissions.warehouse.update,
      ModulePermissions.warehouse.delete,
      ModulePermissions.warehouse.export,
      ModulePermissions.settings.read,
      ModulePermissions.settings.update,
      ModulePermissions.settings.configure,
      ModulePermissions.monitoring.read,
      ModulePermissions.monitoring.configure,
      ModulePermissions.auditLogs.read,
      ModulePermissions.auditLogs.export,
      ModulePermissions.aiAnnotator.create,
      ModulePermissions.aiAnnotator.read,
      ModulePermissions.aiAnnotator.update,
      ModulePermissions.aiAnnotator.delete,
      ModulePermissions.aiAnnotator.configure,
      ModulePermissions.reporting.read,
      ModulePermissions.reporting.create,
      ModulePermissions.reporting.export,
    ],
    module_permissions: {
      user_management: ["create", "read", "update", "delete", "manage"],
      role_management: ["create", "read", "update", "delete", "manage"],
      finance: ["create", "read", "update", "delete", "approve", "export"],
      hr: ["create", "read", "update", "delete", "approve", "export"],
      crm: ["create", "read", "update", "delete", "export"],
      sales: ["create", "read", "update", "delete", "approve", "export"],
      procurement: ["create", "read", "update", "delete", "approve", "export"],
      inventory: ["create", "read", "update", "delete", "export"],
      production: ["create", "read", "update", "delete", "approve", "export"],
      warehouse: ["create", "read", "update", "delete", "export"],
      dashboard: ["read", "export"],
      settings: ["read", "update", "configure"],
      monitoring: ["read", "configure"],
      audit_logs: ["read", "export"],
      ai_annotator: ["create", "read", "update", "delete", "configure"],
      reporting: ["read", "create", "export"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "role_admin",
    name: RoleNames.ADMIN,
    display_name: "Administrator",
    description:
      "Administrative access. Can manage users and configurations but cannot manage system roles.",
    is_system: true,
    is_active: true,
    permissions: [
      ModulePermissions.userManagement.create,
      ModulePermissions.userManagement.read,
      ModulePermissions.userManagement.update,
      ModulePermissions.userManagement.delete,
      ModulePermissions.dashboard.read,
      ModulePermissions.dashboard.export,
      ModulePermissions.finance.create,
      ModulePermissions.finance.read,
      ModulePermissions.finance.update,
      ModulePermissions.finance.delete,
      ModulePermissions.finance.approve,
      ModulePermissions.finance.export,
      ModulePermissions.hr.create,
      ModulePermissions.hr.read,
      ModulePermissions.hr.update,
      ModulePermissions.hr.delete,
      ModulePermissions.hr.approve,
      ModulePermissions.hr.export,
      ModulePermissions.crm.create,
      ModulePermissions.crm.read,
      ModulePermissions.crm.update,
      ModulePermissions.crm.delete,
      ModulePermissions.crm.export,
      ModulePermissions.sales.create,
      ModulePermissions.sales.read,
      ModulePermissions.sales.update,
      ModulePermissions.sales.delete,
      ModulePermissions.sales.approve,
      ModulePermissions.sales.export,
      ModulePermissions.procurement.create,
      ModulePermissions.procurement.read,
      ModulePermissions.procurement.update,
      ModulePermissions.procurement.delete,
      ModulePermissions.procurement.approve,
      ModulePermissions.procurement.export,
      ModulePermissions.inventory.create,
      ModulePermissions.inventory.read,
      ModulePermissions.inventory.update,
      ModulePermissions.inventory.delete,
      ModulePermissions.inventory.export,
      ModulePermissions.production.create,
      ModulePermissions.production.read,
      ModulePermissions.production.update,
      ModulePermissions.production.delete,
      ModulePermissions.production.approve,
      ModulePermissions.production.export,
      ModulePermissions.warehouse.create,
      ModulePermissions.warehouse.read,
      ModulePermissions.warehouse.update,
      ModulePermissions.warehouse.delete,
      ModulePermissions.warehouse.export,
      ModulePermissions.settings.read,
      ModulePermissions.settings.update,
      ModulePermissions.monitoring.read,
      ModulePermissions.auditLogs.read,
      ModulePermissions.auditLogs.export,
      ModulePermissions.reporting.read,
      ModulePermissions.reporting.create,
      ModulePermissions.reporting.export,
    ],
    module_permissions: {
      user_management: ["create", "read", "update", "delete"],
      finance: ["create", "read", "update", "delete", "approve", "export"],
      hr: ["create", "read", "update", "delete", "approve", "export"],
      crm: ["create", "read", "update", "delete", "export"],
      sales: ["create", "read", "update", "delete", "approve", "export"],
      procurement: ["create", "read", "update", "delete", "approve", "export"],
      inventory: ["create", "read", "update", "delete", "export"],
      production: ["create", "read", "update", "delete", "approve", "export"],
      warehouse: ["create", "read", "update", "delete", "export"],
      dashboard: ["read", "export"],
      settings: ["read", "update"],
      monitoring: ["read"],
      audit_logs: ["read", "export"],
      reporting: ["read", "create", "export"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "role_manager",
    name: RoleNames.MANAGER,
    display_name: "Manager",
    description:
      "Can manage team members and approve workflow items. Limited to specific modules.",
    is_system: true,
    is_active: true,
    permissions: [
      ModulePermissions.dashboard.read,
      ModulePermissions.dashboard.export,
      ModulePermissions.userManagement.read,
      ModulePermissions.finance.read,
      ModulePermissions.finance.update,
      ModulePermissions.finance.approve,
      ModulePermissions.finance.export,
      ModulePermissions.hr.read,
      ModulePermissions.hr.update,
      ModulePermissions.hr.approve,
      ModulePermissions.hr.export,
      ModulePermissions.crm.read,
      ModulePermissions.crm.create,
      ModulePermissions.crm.update,
      ModulePermissions.crm.export,
      ModulePermissions.sales.read,
      ModulePermissions.sales.create,
      ModulePermissions.sales.update,
      ModulePermissions.sales.approve,
      ModulePermissions.sales.export,
      ModulePermissions.procurement.read,
      ModulePermissions.procurement.create,
      ModulePermissions.procurement.update,
      ModulePermissions.procurement.approve,
      ModulePermissions.procurement.export,
      ModulePermissions.inventory.read,
      ModulePermissions.inventory.update,
      ModulePermissions.inventory.export,
      ModulePermissions.production.read,
      ModulePermissions.production.update,
      ModulePermissions.production.approve,
      ModulePermissions.production.export,
      ModulePermissions.warehouse.read,
      ModulePermissions.warehouse.update,
      ModulePermissions.warehouse.export,
      ModulePermissions.reporting.read,
      ModulePermissions.reporting.export,
    ],
    module_permissions: {
      dashboard: ["read", "export"],
      user_management: ["read"],
      finance: ["read", "update", "approve", "export"],
      hr: ["read", "update", "approve", "export"],
      crm: ["read", "create", "update", "export"],
      sales: ["read", "create", "update", "approve", "export"],
      procurement: ["read", "create", "update", "approve", "export"],
      inventory: ["read", "update", "export"],
      production: ["read", "update", "approve", "export"],
      warehouse: ["read", "update", "export"],
      reporting: ["read", "export"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "role_supervisor",
    name: RoleNames.SUPERVISOR,
    display_name: "Supervisor",
    description: "Can supervise team work. Can read and update team data.",
    is_system: true,
    is_active: true,
    permissions: [
      ModulePermissions.dashboard.read,
      ModulePermissions.userManagement.read,
      ModulePermissions.finance.read,
      ModulePermissions.finance.export,
      ModulePermissions.hr.read,
      ModulePermissions.hr.export,
      ModulePermissions.crm.read,
      ModulePermissions.crm.update,
      ModulePermissions.crm.export,
      ModulePermissions.sales.read,
      ModulePermissions.sales.create,
      ModulePermissions.sales.update,
      ModulePermissions.sales.export,
      ModulePermissions.procurement.read,
      ModulePermissions.procurement.update,
      ModulePermissions.procurement.export,
      ModulePermissions.inventory.read,
      ModulePermissions.inventory.update,
      ModulePermissions.inventory.export,
      ModulePermissions.production.read,
      ModulePermissions.production.update,
      ModulePermissions.production.export,
      ModulePermissions.warehouse.read,
      ModulePermissions.warehouse.update,
      ModulePermissions.warehouse.export,
      ModulePermissions.reporting.read,
      ModulePermissions.reporting.export,
    ],
    module_permissions: {
      dashboard: ["read"],
      user_management: ["read"],
      finance: ["read", "export"],
      hr: ["read", "export"],
      crm: ["read", "update", "export"],
      sales: ["read", "create", "update", "export"],
      procurement: ["read", "update", "export"],
      inventory: ["read", "update", "export"],
      production: ["read", "update", "export"],
      warehouse: ["read", "update", "export"],
      reporting: ["read", "export"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "role_user",
    name: RoleNames.USER,
    display_name: "User",
    description:
      "Standard user access. Can read and create data in assigned modules.",
    is_system: true,
    is_active: true,
    permissions: [
      ModulePermissions.dashboard.read,
      ModulePermissions.crm.read,
      ModulePermissions.crm.create,
      ModulePermissions.sales.read,
      ModulePermissions.sales.create,
      ModulePermissions.procurement.read,
      ModulePermissions.inventory.read,
      ModulePermissions.production.read,
      ModulePermissions.warehouse.read,
      ModulePermissions.reporting.read,
    ],
    module_permissions: {
      dashboard: ["read"],
      crm: ["read", "create"],
      sales: ["read", "create"],
      procurement: ["read"],
      inventory: ["read"],
      production: ["read"],
      warehouse: ["read"],
      reporting: ["read"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "role_viewer",
    name: RoleNames.VIEWER,
    display_name: "Viewer",
    description: "Read-only access. Can view data but cannot create or modify.",
    is_system: true,
    is_active: true,
    permissions: [
      ModulePermissions.dashboard.read,
      ModulePermissions.finance.read,
      ModulePermissions.hr.read,
      ModulePermissions.crm.read,
      ModulePermissions.sales.read,
      ModulePermissions.procurement.read,
      ModulePermissions.inventory.read,
      ModulePermissions.production.read,
      ModulePermissions.warehouse.read,
      ModulePermissions.reporting.read,
    ],
    module_permissions: {
      dashboard: ["read"],
      finance: ["read"],
      hr: ["read"],
      crm: ["read"],
      sales: ["read"],
      procurement: ["read"],
      inventory: ["read"],
      production: ["read"],
      warehouse: ["read"],
      reporting: ["read"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "role_guest",
    name: RoleNames.GUEST,
    display_name: "Guest",
    description:
      "Limited guest access. Can only access public dashboards and reports.",
    is_system: true,
    is_active: true,
    permissions: [
      ModulePermissions.dashboard.read,
      ModulePermissions.reporting.read,
    ],
    module_permissions: {
      dashboard: ["read"],
      reporting: ["read"],
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

/**
 * Role Hierarchy Definition
 * Lower level numbers = higher privileges
 */
export const ROLE_HIERARCHY: RoleHierarchy[] = [
  {
    role: RoleNames.SUPER_ADMIN,
    level: 0,
    inherits_from: [],
  },
  {
    role: RoleNames.ADMIN,
    level: 1,
    inherits_from: [],
  },
  {
    role: RoleNames.MANAGER,
    level: 2,
    inherits_from: [RoleNames.USER],
  },
  {
    role: RoleNames.SUPERVISOR,
    level: 3,
    inherits_from: [RoleNames.USER],
  },
  {
    role: RoleNames.USER,
    level: 4,
    inherits_from: [RoleNames.VIEWER],
  },
  {
    role: RoleNames.VIEWER,
    level: 5,
    inherits_from: [RoleNames.GUEST],
  },
  {
    role: RoleNames.GUEST,
    level: 6,
    inherits_from: [],
  },
];

/**
 * Permission groups for easier management
 */
export const PERMISSION_GROUPS = {
  admin: [
    ModulePermissions.userManagement.manage,
    ModulePermissions.roleManagement.manage,
  ],
  finance: [
    ModulePermissions.finance.create,
    ModulePermissions.finance.read,
    ModulePermissions.finance.update,
    ModulePermissions.finance.delete,
    ModulePermissions.finance.approve,
  ],
  hr: [
    ModulePermissions.hr.create,
    ModulePermissions.hr.read,
    ModulePermissions.hr.update,
    ModulePermissions.hr.delete,
    ModulePermissions.hr.approve,
  ],
  sales: [
    ModulePermissions.sales.create,
    ModulePermissions.sales.read,
    ModulePermissions.sales.update,
    ModulePermissions.sales.delete,
    ModulePermissions.sales.approve,
  ],
  procurement: [
    ModulePermissions.procurement.create,
    ModulePermissions.procurement.read,
    ModulePermissions.procurement.update,
    ModulePermissions.procurement.delete,
    ModulePermissions.procurement.approve,
  ],
  viewOnly: [
    ModulePermissions.dashboard.read,
    ModulePermissions.finance.read,
    ModulePermissions.hr.read,
    ModulePermissions.crm.read,
    ModulePermissions.sales.read,
    ModulePermissions.procurement.read,
    ModulePermissions.inventory.read,
    ModulePermissions.reporting.read,
  ],
};
