// SPDX-License-Identifier: MIT
// apps/backend/src/types/settings-definitions.ts

/**
 * Comprehensive Settings Definitions for ERP System
 * All configurable settings with validation rules and metadata
 */

import { SettingDefinition } from "./settings_old.js";

export const SETTING_DEFINITIONS: SettingDefinition[] = [
  // ============================================================
  // SYSTEM SETTINGS
  // ============================================================
  {
    key: "system_name",
    category: "system",
    type: "string",
    label: "System Name",
    description: "Name des ERP-Systems",
    defaultValue: "ERP SteinmetZ",
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "system_company_name",
    category: "system",
    type: "string",
    label: "Firmenname",
    description: "Offizieller Firmenname",
    defaultValue: "SteinmetZ GmbH",
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "system_description",
    category: "system",
    type: "string",
    label: "System Beschreibung",
    description: "Kurze Beschreibung des Systems",
    defaultValue: "Enterprise Resource Planning System",
    required: false,
    sensitive: false,
    group: "general",
  },
  {
    key: "system_timezone",
    category: "system",
    type: "select",
    label: "Zeitzone",
    description: "Standard-Zeitzone für das System",
    defaultValue: "Europe/Berlin",
    required: true,
    sensitive: false,
    validation: {
      options: [
        "Europe/Berlin",
        "Europe/London",
        "Europe/Paris",
        "America/New_York",
        "America/Los_Angeles",
        "Asia/Tokyo",
        "Australia/Sydney",
      ],
    },
    group: "localization",
  },
  {
    key: "system_country",
    category: "system",
    type: "select",
    label: "Land",
    description: "Hauptstandort des Unternehmens",
    defaultValue: "DE",
    required: true,
    sensitive: false,
    validation: {
      options: ["DE", "AT", "CH", "US", "GB", "FR", "IT", "ES", "PL", "CN"],
    },
    group: "localization",
  },
  {
    key: "system_currency",
    category: "system",
    type: "select",
    label: "Währung",
    description: "Standard-Währung",
    defaultValue: "EUR",
    required: true,
    sensitive: false,
    validation: {
      options: ["EUR", "USD", "GBP", "CHF", "JPY", "CNY"],
    },
    group: "localization",
  },
  {
    key: "maintenance_mode",
    category: "system",
    type: "boolean",
    label: "Wartungsmodus",
    description: "System in Wartungsmodus versetzen (nur Admins haben Zugriff)",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "maintenance_message",
    category: "system",
    type: "string",
    label: "Wartungsnachricht",
    description: "Nachricht die während des Wartungsmodus angezeigt wird",
    defaultValue: "System wird gewartet. Bitte später erneut versuchen.",
    required: false,
    sensitive: false,
    group: "general",
  },
  {
    key: "debug_mode",
    category: "system",
    type: "boolean",
    label: "Debug-Modus",
    description: "Ausführliche Fehlerausgaben aktivieren",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "development",
  },
  {
    key: "log_level",
    category: "system",
    type: "select",
    label: "Log-Level",
    description: "Detailgrad der System-Logs",
    defaultValue: "info",
    required: true,
    sensitive: false,
    validation: {
      options: ["debug", "info", "warn", "error", "fatal"],
    },
    group: "logging",
  },
  {
    key: "log_retention_days",
    category: "system",
    type: "number",
    label: "Log-Aufbewahrung (Tage)",
    description: "Wie lange sollen Logs gespeichert werden",
    defaultValue: 90,
    required: true,
    sensitive: false,
    validation: {
      min: 7,
      max: 365,
    },
    group: "logging",
  },

  // ============================================================
  // TENANT (MANDANTENFÄHIGKEIT) SETTINGS
  // ============================================================
  {
    key: "tenant_enabled",
    category: "system",
    type: "boolean",
    label: "Mandantenfähigkeit aktiviert",
    description: "Multi-Tenant-Funktionalität aktivieren",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "tenant",
    requiresRestart: true,
  },
  {
    key: "tenant_mode",
    category: "system",
    type: "select",
    label: "Mandanten-Modus",
    description: "Einzelner oder mehrere Mandanten",
    defaultValue: "single",
    required: true,
    sensitive: false,
    validation: {
      options: ["single", "multi"],
    },
    group: "tenant",
    requiresRestart: true,
  },
  {
    key: "tenant_isolation",
    category: "system",
    type: "select",
    label: "Daten-Isolierung",
    description: "Art der Mandanten-Datenisolierung",
    defaultValue: "row",
    required: true,
    sensitive: false,
    validation: {
      options: ["database", "schema", "row"],
    },
    group: "tenant",
    requiresRestart: true,
  },
  {
    key: "tenant_default_id",
    category: "system",
    type: "string",
    label: "Standard-Mandanten-ID",
    description: "ID des Standard-Mandanten",
    defaultValue: "",
    required: false,
    sensitive: false,
    group: "tenant",
  },
  {
    key: "tenant_custom_domains",
    category: "system",
    type: "boolean",
    label: "Eigene Domains",
    description: "Mandanten können eigene Domains verwenden",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "tenant",
  },
  {
    key: "tenant_data_isolation_strict",
    category: "system",
    type: "boolean",
    label: "Strikte Datenisolierung",
    description: "Strikte Trennung der Mandantendaten erzwingen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "tenant",
  },

  // ============================================================
  // AI SETTINGS
  // ============================================================
  {
    key: "ai_enabled",
    category: "ai",
    type: "boolean",
    label: "KI aktiviert",
    description: "KI-Funktionen im System aktivieren",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "default_provider",
    category: "ai",
    type: "select",
    label: "Standard KI-Provider",
    description: "Welcher KI-Provider standardmäßig verwendet wird",
    defaultValue: "openai",
    required: true,
    sensitive: false,
    validation: {
      options: ["openai", "anthropic", "ollama", "local", "azure", "gemini"],
    },
    group: "provider",
  },
  {
    key: "default_model",
    category: "ai",
    type: "string",
    label: "Standard Modell",
    description: "Standard KI-Modell",
    defaultValue: "gpt-4o-mini",
    required: true,
    sensitive: false,
    group: "provider",
  },
  {
    key: "ai_timeout_seconds",
    category: "ai",
    type: "number",
    label: "KI Timeout (Sekunden)",
    description: "Maximale Wartezeit für KI-Antworten",
    defaultValue: 60,
    required: true,
    sensitive: false,
    validation: {
      min: 10,
      max: 300,
    },
    group: "general",
  },
  {
    key: "max_parallel_requests",
    category: "ai",
    type: "number",
    label: "Parallele Anfragen",
    description: "Maximale Anzahl gleichzeitiger KI-Anfragen",
    defaultValue: 3,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 10,
    },
    group: "performance",
  },
  {
    key: "ai_cost_limit_monthly",
    category: "ai",
    type: "number",
    label: "Monatliches Kosten-Limit",
    description: "Maximale monatliche Kosten für KI-APIs (€)",
    defaultValue: 1000,
    required: false,
    sensitive: false,
    validation: {
      min: 0,
      max: 100000,
    },
    group: "billing",
  },

  // OpenAI Settings
  {
    key: "openai_api_key",
    category: "ai",
    type: "string",
    label: "OpenAI API Key",
    description: "API-Schlüssel für OpenAI",
    defaultValue: "",
    required: false,
    sensitive: true,
    group: "openai",
  },
  {
    key: "openai_organization",
    category: "ai",
    type: "string",
    label: "OpenAI Organization ID",
    description: "Organisation-ID (optional)",
    defaultValue: "",
    required: false,
    sensitive: true,
    group: "openai",
  },
  {
    key: "openai_model",
    category: "ai",
    type: "select",
    label: "OpenAI Modell",
    description: "Welches OpenAI Modell verwenden",
    defaultValue: "gpt-4o-mini",
    required: true,
    sensitive: false,
    validation: {
      options: [
        "gpt-4o",
        "gpt-4o-mini",
        "gpt-4-turbo",
        "gpt-4",
        "gpt-3.5-turbo",
        "o1",
        "o1-mini",
      ],
    },
    group: "openai",
  },
  {
    key: "openai_temperature",
    category: "ai",
    type: "number",
    label: "OpenAI Temperatur",
    description:
      "Kreativität der KI (0.0 = deterministisch, 2.0 = sehr kreativ)",
    defaultValue: 0.7,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 2,
    },
    group: "openai",
  },
  {
    key: "openai_max_tokens",
    category: "ai",
    type: "number",
    label: "OpenAI Max Tokens",
    description: "Maximale Länge der Antwort",
    defaultValue: 4096,
    required: true,
    sensitive: false,
    validation: {
      min: 100,
      max: 128000,
    },
    group: "openai",
  },
  {
    key: "openai_top_p",
    category: "ai",
    type: "number",
    label: "OpenAI Top P",
    description: "Nucleus sampling Parameter",
    defaultValue: 1.0,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 1,
    },
    group: "openai",
  },
  {
    key: "openai_frequency_penalty",
    category: "ai",
    type: "number",
    label: "OpenAI Frequency Penalty",
    description: "Bestrafung für häufige Token",
    defaultValue: 0.0,
    required: true,
    sensitive: false,
    validation: {
      min: -2,
      max: 2,
    },
    group: "openai",
  },
  {
    key: "openai_presence_penalty",
    category: "ai",
    type: "number",
    label: "OpenAI Presence Penalty",
    description: "Bestrafung für bereits vorhandene Token",
    defaultValue: 0.0,
    required: true,
    sensitive: false,
    validation: {
      min: -2,
      max: 2,
    },
    group: "openai",
  },

  // Anthropic Settings
  {
    key: "anthropic_api_key",
    category: "ai",
    type: "string",
    label: "Anthropic API Key",
    description: "API-Schlüssel für Anthropic Claude",
    defaultValue: "",
    required: false,
    sensitive: true,
    group: "anthropic",
  },
  {
    key: "anthropic_model",
    category: "ai",
    type: "select",
    label: "Anthropic Modell",
    description: "Welches Claude Modell verwenden",
    defaultValue: "claude-3-5-sonnet-20241022",
    required: true,
    sensitive: false,
    validation: {
      options: [
        "claude-3-5-sonnet-20241022",
        "claude-3-opus-20240229",
        "claude-3-sonnet-20240229",
        "claude-3-haiku-20240307",
      ],
    },
    group: "anthropic",
  },
  {
    key: "anthropic_temperature",
    category: "ai",
    type: "number",
    label: "Anthropic Temperatur",
    description: "Kreativität (0.0 - 1.0)",
    defaultValue: 0.7,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 1,
    },
    group: "anthropic",
  },
  {
    key: "anthropic_max_tokens",
    category: "ai",
    type: "number",
    label: "Anthropic Max Tokens",
    description: "Maximale Länge der Antwort",
    defaultValue: 4096,
    required: true,
    sensitive: false,
    validation: {
      min: 100,
      max: 200000,
    },
    group: "anthropic",
  },

  // Ollama Settings
  {
    key: "ollama_base_url",
    category: "ai",
    type: "string",
    label: "Ollama Base URL",
    description: "Ollama Server URL",
    defaultValue: "http://localhost:11434",
    required: true,
    sensitive: false,
    group: "ollama",
  },
  {
    key: "ollama_model",
    category: "ai",
    type: "string",
    label: "Ollama Modell",
    description: "Name des lokalen Modells",
    defaultValue: "qwen2.5:3b",
    required: true,
    sensitive: false,
    group: "ollama",
  },

  // ============================================================
  // SECURITY SETTINGS
  // ============================================================
  {
    key: "session_timeout_minutes",
    category: "security",
    type: "number",
    label: "Session Timeout",
    description: "Automatischer Logout nach X Minuten Inaktivität",
    defaultValue: 60,
    required: true,
    sensitive: false,
    validation: {
      min: 5,
      max: 1440,
    },
    group: "authentication",
  },
  {
    key: "max_login_attempts",
    category: "security",
    type: "number",
    label: "Maximale Login-Versuche",
    description: "Anzahl fehlgeschlagener Login-Versuche vor Sperre",
    defaultValue: 5,
    required: true,
    sensitive: false,
    validation: {
      min: 3,
      max: 20,
    },
    group: "authentication",
  },
  {
    key: "lockout_duration_minutes",
    category: "security",
    type: "number",
    label: "Sperrdauer (Minuten)",
    description: "Dauer der Account-Sperre nach zu vielen Fehlversuchen",
    defaultValue: 30,
    required: true,
    sensitive: false,
    validation: {
      min: 5,
      max: 1440,
    },
    group: "authentication",
  },
  {
    key: "password_min_length",
    category: "security",
    type: "number",
    label: "Passwort Mindestlänge",
    description: "Minimale Anzahl Zeichen für Passwörter",
    defaultValue: 8,
    required: true,
    sensitive: false,
    validation: {
      min: 6,
      max: 32,
    },
    group: "password_policy",
  },
  {
    key: "password_require_uppercase",
    category: "security",
    type: "boolean",
    label: "Großbuchstaben erforderlich",
    description: "Passwort muss mindestens einen Großbuchstaben enthalten",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "password_policy",
  },
  {
    key: "password_require_lowercase",
    category: "security",
    type: "boolean",
    label: "Kleinbuchstaben erforderlich",
    description: "Passwort muss mindestens einen Kleinbuchstaben enthalten",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "password_policy",
  },
  {
    key: "password_require_numbers",
    category: "security",
    type: "boolean",
    label: "Zahlen erforderlich",
    description: "Passwort muss mindestens eine Zahl enthalten",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "password_policy",
  },
  {
    key: "password_require_special",
    category: "security",
    type: "boolean",
    label: "Sonderzeichen erforderlich",
    description: "Passwort muss mindestens ein Sonderzeichen enthalten",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "password_policy",
  },
  {
    key: "password_expiry_days",
    category: "security",
    type: "number",
    label: "Passwort-Ablauf (Tage)",
    description:
      "Nach wie vielen Tagen muss das Passwort geändert werden (0 = nie)",
    defaultValue: 90,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 365,
    },
    group: "password_policy",
  },
  {
    key: "require_2fa",
    category: "security",
    type: "boolean",
    label: "2FA erforderlich",
    description: "Zwei-Faktor-Authentifizierung für alle Benutzer erzwingen",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "authentication",
  },
  {
    key: "jwt_expiry_hours",
    category: "security",
    type: "number",
    label: "JWT Ablaufzeit (Stunden)",
    description: "Gültigkeit des JWT Access Tokens",
    defaultValue: 24,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 720,
    },
    group: "tokens",
  },
  {
    key: "cors_enabled",
    category: "security",
    type: "boolean",
    label: "CORS aktiviert",
    description: "Cross-Origin Resource Sharing erlauben",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "api_security",
  },

  // ============================================================
  // UI SETTINGS
  // ============================================================
  {
    key: "theme",
    category: "ui",
    type: "select",
    label: "Theme",
    description: "Farbschema der Benutzeroberfläche",
    defaultValue: "auto",
    required: true,
    sensitive: false,
    validation: {
      options: ["light", "dark", "auto", "lcars"],
    },
    group: "appearance",
  },
  {
    key: "language",
    category: "ui",
    type: "select",
    label: "Sprache",
    description: "Systemsprache",
    defaultValue: "de",
    required: true,
    sensitive: false,
    validation: {
      options: [
        "de",
        "en",
        "fr",
        "es",
        "it",
        "pl",
        "tr",
        "ar",
        "zh",
        "ru",
        "nds",
      ],
    },
    group: "localization",
  },
  {
    key: "date_format",
    category: "ui",
    type: "select",
    label: "Datumsformat",
    description: "Wie Datumsangaben angezeigt werden",
    defaultValue: "DD.MM.YYYY",
    required: true,
    sensitive: false,
    validation: {
      options: [
        "DD.MM.YYYY",
        "MM/DD/YYYY",
        "YYYY-MM-DD",
        "DD/MM/YYYY",
        "YYYY/MM/DD",
      ],
    },
    group: "formatting",
  },
  {
    key: "time_format",
    category: "ui",
    type: "select",
    label: "Zeitformat",
    description: "12-Stunden oder 24-Stunden Format",
    defaultValue: "HH:mm",
    required: true,
    sensitive: false,
    validation: {
      options: ["HH:mm", "hh:mm A", "HH:mm:ss", "hh:mm:ss A"],
    },
    group: "formatting",
  },
  {
    key: "decimal_separator",
    category: "ui",
    type: "select",
    label: "Dezimaltrennzeichen",
    description: "Trennzeichen für Dezimalzahlen",
    defaultValue: ",",
    required: true,
    sensitive: false,
    validation: {
      options: [",", "."],
    },
    group: "formatting",
  },
  {
    key: "thousand_separator",
    category: "ui",
    type: "select",
    label: "Tausendertrennzeichen",
    description: "Trennzeichen für Tausender",
    defaultValue: ".",
    required: true,
    sensitive: false,
    validation: {
      options: [".", ",", " ", ""],
    },
    group: "formatting",
  },
  {
    key: "items_per_page",
    category: "ui",
    type: "select",
    label: "Einträge pro Seite",
    description: "Standard-Anzahl Einträge in Tabellen",
    defaultValue: 25,
    required: true,
    sensitive: false,
    validation: {
      options: ["10", "25", "50", "100", "200"],
    },
    group: "display",
  },
  {
    key: "show_tooltips",
    category: "ui",
    type: "boolean",
    label: "Tooltips anzeigen",
    description: "Hilfe-Tooltips beim Hover aktivieren",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "display",
  },
  {
    key: "enable_animations",
    category: "ui",
    type: "boolean",
    label: "Animationen aktivieren",
    description: "UI-Animationen und Übergänge",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "display",
  },
  {
    key: "compact_view",
    category: "ui",
    type: "boolean",
    label: "Kompakte Ansicht",
    description: "Dichtere Darstellung mit weniger Abständen",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "display",
  },
  {
    key: "sidebar_collapsed",
    category: "ui",
    type: "boolean",
    label: "Sidebar eingeklappt",
    description: "Seitenleiste standardmäßig eingeklappt",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "layout",
  },

  // ============================================================
  // DATABASE SETTINGS
  // ============================================================
  {
    key: "db_backup_enabled",
    category: "database",
    type: "boolean",
    label: "Backups aktiviert",
    description: "Automatische Datenbank-Backups",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "backup",
  },
  {
    key: "db_backup_interval_hours",
    category: "database",
    type: "number",
    label: "Backup-Intervall (Stunden)",
    description: "Zeitabstand zwischen automatischen Backups",
    defaultValue: 24,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 168,
    },
    group: "backup",
  },
  {
    key: "db_backup_retention_days",
    category: "database",
    type: "number",
    label: "Backup-Aufbewahrung (Tage)",
    description: "Wie lange Backups gespeichert werden",
    defaultValue: 30,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 365,
    },
    group: "backup",
  },
  {
    key: "db_max_connections",
    category: "database",
    type: "number",
    label: "Max. Verbindungen",
    description: "Maximale Anzahl gleichzeitiger DB-Verbindungen",
    defaultValue: 20,
    required: true,
    sensitive: false,
    validation: {
      min: 5,
      max: 100,
    },
    group: "performance",
  },
  {
    key: "db_pool_size",
    category: "database",
    type: "number",
    label: "Connection Pool Größe",
    description: "Anzahl vorgehaltener Verbindungen im Pool",
    defaultValue: 10,
    required: true,
    sensitive: false,
    validation: {
      min: 2,
      max: 50,
    },
    group: "performance",
  },

  // ============================================================
  // PERFORMANCE SETTINGS
  // ============================================================
  {
    key: "cache_enabled",
    category: "performance",
    type: "boolean",
    label: "Caching aktiviert",
    description: "Server-seitiges Caching für bessere Performance",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "caching",
  },
  {
    key: "cache_ttl_minutes",
    category: "performance",
    type: "number",
    label: "Cache TTL (Minuten)",
    description: "Time-To-Live für Cache-Einträge",
    defaultValue: 60,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 1440,
    },
    group: "caching",
  },
  {
    key: "rate_limit_enabled",
    category: "performance",
    type: "boolean",
    label: "Rate Limiting aktiviert",
    description: "API-Anfragen pro Zeiteinheit begrenzen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "api",
  },
  {
    key: "rate_limit_requests_per_minute",
    category: "performance",
    type: "number",
    label: "Rate Limit (Anfragen/Min)",
    description: "Maximale Anfragen pro Minute",
    defaultValue: 100,
    required: true,
    sensitive: false,
    validation: {
      min: 10,
      max: 10000,
    },
    group: "api",
  },
  {
    key: "compression_enabled",
    category: "performance",
    type: "boolean",
    label: "Komprimierung aktiviert",
    description: "Gzip-Komprimierung für HTTP-Antworten",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "optimization",
  },

  // ============================================================
  // EMAIL SETTINGS
  // ============================================================
  {
    key: "email_enabled",
    category: "email",
    type: "boolean",
    label: "Email aktiviert",
    description: "Email-Versand aus dem System heraus",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "email_provider",
    category: "email",
    type: "select",
    label: "Email Provider",
    description: "Welcher Service für Email-Versand",
    defaultValue: "smtp",
    required: true,
    sensitive: false,
    validation: {
      options: ["smtp", "sendgrid", "mailgun", "ses"],
    },
    group: "general",
  },
  {
    key: "email_smtp_host",
    category: "email",
    type: "string",
    label: "SMTP Host",
    description: "SMTP Server Adresse",
    defaultValue: "",
    required: false,
    sensitive: false,
    group: "smtp",
  },
  {
    key: "email_smtp_port",
    category: "email",
    type: "number",
    label: "SMTP Port",
    description: "SMTP Server Port",
    defaultValue: 587,
    required: false,
    sensitive: false,
    validation: {
      min: 1,
      max: 65535,
    },
    group: "smtp",
  },
  {
    key: "email_smtp_user",
    category: "email",
    type: "string",
    label: "SMTP Benutzername",
    description: "Benutzername für SMTP-Authentifizierung",
    defaultValue: "",
    required: false,
    sensitive: false,
    group: "smtp",
  },
  {
    key: "email_smtp_password",
    category: "email",
    type: "string",
    label: "SMTP Passwort",
    description: "Passwort für SMTP-Authentifizierung",
    defaultValue: "",
    required: false,
    sensitive: true,
    group: "smtp",
  },
  {
    key: "email_from_address",
    category: "email",
    type: "string",
    label: "Absender Email",
    description: "Standard Absender-Adresse",
    defaultValue: "",
    required: false,
    sensitive: false,
    group: "general",
  },
  {
    key: "email_from_name",
    category: "email",
    type: "string",
    label: "Absender Name",
    description: "Name des Absenders",
    defaultValue: "",
    required: false,
    sensitive: false,
    group: "general",
  },

  // ============================================================
  // FINANCE MODULE
  // ============================================================
  {
    key: "finance_enabled",
    category: "finance",
    type: "boolean",
    label: "Finance Modul aktiviert",
    description: "Finanzbuchhaltung und Rechnungswesen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "finance_fiscal_year_start",
    category: "finance",
    type: "string",
    label: "Geschäftsjahrbeginn",
    description: "Start des Geschäftsjahrs (MM-DD)",
    defaultValue: "01-01",
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "finance_default_tax_rate",
    category: "finance",
    type: "number",
    label: "Standard Steuersatz (%)",
    description: "Standard-Mehrwertsteuersatz",
    defaultValue: 19.0,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 50,
    },
    group: "taxes",
  },
  {
    key: "finance_auto_invoice_numbering",
    category: "finance",
    type: "boolean",
    label: "Automatische Rechnungsnummern",
    description: "Rechnungsnummern automatisch vergeben",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "invoicing",
  },
  {
    key: "finance_invoice_prefix",
    category: "finance",
    type: "string",
    label: "Rechnungsnummer-Präfix",
    description: "Präfix für Rechnungsnummern",
    defaultValue: "INV-",
    required: true,
    sensitive: false,
    group: "invoicing",
  },
  {
    key: "finance_payment_terms_days",
    category: "finance",
    type: "number",
    label: "Zahlungsziel (Tage)",
    description: "Standard-Zahlungsziel in Tagen",
    defaultValue: 30,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 365,
    },
    group: "invoicing",
  },
  {
    key: "finance_accounting_standard",
    category: "finance",
    type: "select",
    label: "Rechnungslegungsstandard",
    description: "Welcher Accounting-Standard",
    defaultValue: "HGB",
    required: true,
    sensitive: false,
    validation: {
      options: ["GAAP", "IFRS", "HGB"],
    },
    group: "general",
  },

  // ============================================================
  // INVENTORY MODULE
  // ============================================================
  {
    key: "inventory_enabled",
    category: "inventory",
    type: "boolean",
    label: "Lager-Modul aktiviert",
    description: "Lagerverwaltung und Bestandsführung",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "inventory_track_lots",
    category: "inventory",
    type: "boolean",
    label: "Chargen-Tracking",
    description: "Verfolgung von Produktionschargen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "tracking",
  },
  {
    key: "inventory_track_serial_numbers",
    category: "inventory",
    type: "boolean",
    label: "Seriennummer-Tracking",
    description: "Verfolgung einzelner Seriennummern",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "tracking",
  },
  {
    key: "inventory_low_stock_threshold",
    category: "inventory",
    type: "number",
    label: "Mindestbestand-Schwelle",
    description: "Warnung bei Unterschreitung dieses Bestands",
    defaultValue: 10,
    required: true,
    sensitive: false,
    validation: {
      min: 0,
      max: 10000,
    },
    group: "alerts",
  },
  {
    key: "inventory_reorder_point_enabled",
    category: "inventory",
    type: "boolean",
    label: "Meldebestand aktiviert",
    description: "Automatische Bestellvorschläge bei Mindestbestand",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "purchasing",
  },
  {
    key: "inventory_barcode_format",
    category: "inventory",
    type: "select",
    label: "Barcode-Format",
    description: "Standard-Format für Barcodes",
    defaultValue: "EAN13",
    required: true,
    sensitive: false,
    validation: {
      options: ["EAN13", "UPC", "CODE128", "QR"],
    },
    group: "barcodes",
  },
  {
    key: "inventory_stock_valuation_method",
    category: "inventory",
    type: "select",
    label: "Bestandsbewertung",
    description: "Methode zur Bestandsbewertung",
    defaultValue: "FIFO",
    required: true,
    sensitive: false,
    validation: {
      options: ["FIFO", "LIFO", "Average"],
    },
    group: "valuation",
  },

  // ============================================================
  // HR MODULE
  // ============================================================
  {
    key: "hr_enabled",
    category: "hr",
    type: "boolean",
    label: "HR-Modul aktiviert",
    description: "Personalverwaltung und Zeiterfassung",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "hr_timesheet_enabled",
    category: "hr",
    type: "boolean",
    label: "Zeiterfassung aktiviert",
    description: "Mitarbeiter können Arbeitszeiten erfassen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "time_tracking",
  },
  {
    key: "hr_attendance_tracking",
    category: "hr",
    type: "boolean",
    label: "Anwesenheitserfassung",
    description: "Erfassung von Ein-/Ausstempelungen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "time_tracking",
  },
  {
    key: "hr_leave_management",
    category: "hr",
    type: "boolean",
    label: "Urlaubsverwaltung",
    description: "Verwaltung von Urlaubsanträgen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "absence",
  },
  {
    key: "hr_working_hours_per_week",
    category: "hr",
    type: "number",
    label: "Wochenstunden",
    description: "Standard-Arbeitszeit pro Woche",
    defaultValue: 40,
    required: true,
    sensitive: false,
    validation: {
      min: 10,
      max: 80,
    },
    group: "working_time",
  },
  {
    key: "hr_overtime_multiplier",
    category: "hr",
    type: "number",
    label: "Überstunden-Faktor",
    description: "Vergütungsfaktor für Überstunden",
    defaultValue: 1.5,
    required: true,
    sensitive: false,
    validation: {
      min: 1.0,
      max: 3.0,
    },
    group: "working_time",
  },

  // ============================================================
  // CRM MODULE
  // ============================================================
  {
    key: "crm_enabled",
    category: "crm",
    type: "boolean",
    label: "CRM-Modul aktiviert",
    description: "Customer Relationship Management",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "crm_lead_scoring",
    category: "crm",
    type: "boolean",
    label: "Lead Scoring aktiviert",
    description: "Automatische Bewertung von Leads",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "leads",
  },
  {
    key: "crm_quote_validity_days",
    category: "crm",
    type: "number",
    label: "Angebotsgültigkeit (Tage)",
    description: "Wie lange sind Angebote gültig",
    defaultValue: 30,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 365,
    },
    group: "quotes",
  },
  {
    key: "crm_follow_up_reminder_days",
    category: "crm",
    type: "number",
    label: "Follow-up Erinnerung (Tage)",
    description: "Nach wie vielen Tagen an Follow-up erinnern",
    defaultValue: 7,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 90,
    },
    group: "leads",
  },
  {
    key: "crm_duplicate_detection",
    category: "crm",
    type: "boolean",
    label: "Duplikat-Erkennung",
    description: "Warnung bei möglichen Duplikaten",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "data_quality",
  },

  // ============================================================
  // REPORTING MODULE
  // ============================================================
  {
    key: "reporting_enabled",
    category: "reporting",
    type: "boolean",
    label: "Reporting aktiviert",
    description: "Berichtswesen und Analytics",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "reporting_auto_generate_monthly",
    category: "reporting",
    type: "boolean",
    label: "Monatliche Auto-Reports",
    description: "Automatische Generierung monatlicher Berichte",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "automation",
  },
  {
    key: "reporting_dashboard_refresh_interval",
    category: "reporting",
    type: "number",
    label: "Dashboard Refresh (Sekunden)",
    description: "Aktualisierungsintervall für Dashboards",
    defaultValue: 300,
    required: true,
    sensitive: false,
    validation: {
      min: 30,
      max: 3600,
    },
    group: "dashboards",
  },
  {
    key: "reporting_data_retention_months",
    category: "reporting",
    type: "number",
    label: "Datenaufbewahrung (Monate)",
    description: "Wie lange werden Reporting-Daten gespeichert",
    defaultValue: 24,
    required: true,
    sensitive: false,
    validation: {
      min: 3,
      max: 120,
    },
    group: "data_retention",
  },
  {
    key: "reporting_chart_library",
    category: "reporting",
    type: "select",
    label: "Chart Library",
    description: "Welche Bibliothek für Diagramme",
    defaultValue: "chartjs",
    required: true,
    sensitive: false,
    validation: {
      options: ["chartjs", "d3", "recharts"],
    },
    group: "visualization",
  },

  // ============================================================
  // NOTIFICATIONS
  // ============================================================
  {
    key: "notifications_enabled",
    category: "notifications",
    type: "boolean",
    label: "Benachrichtigungen aktiviert",
    description: "Systemweite Benachrichtigungen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "notifications_email",
    category: "notifications",
    type: "boolean",
    label: "Email-Benachrichtigungen",
    description: "Benachrichtigungen per Email",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "channels",
  },
  {
    key: "notifications_browser",
    category: "notifications",
    type: "boolean",
    label: "Browser-Benachrichtigungen",
    description: "Push-Notifications im Browser",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "channels",
  },
  {
    key: "notification_sound_enabled",
    category: "notifications",
    type: "boolean",
    label: "Sound aktiviert",
    description: "Ton bei neuen Benachrichtigungen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "preferences",
  },

  // ============================================================
  // API SETTINGS
  // ============================================================
  {
    key: "api_enabled",
    category: "api",
    type: "boolean",
    label: "REST API aktiviert",
    description: "Externer API-Zugriff erlauben",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "api_rate_limiting",
    category: "api",
    type: "boolean",
    label: "API Rate Limiting",
    description: "Anfragen-Limitierung für API",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "security",
  },
  {
    key: "api_rate_limit_per_hour",
    category: "api",
    type: "number",
    label: "API Rate Limit (pro Stunde)",
    description: "Maximale API-Anfragen pro Stunde",
    defaultValue: 1000,
    required: true,
    sensitive: false,
    validation: {
      min: 10,
      max: 100000,
    },
    group: "security",
  },
  {
    key: "api_documentation_enabled",
    category: "api",
    type: "boolean",
    label: "API Dokumentation",
    description: "Swagger/OpenAPI Dokumentation anzeigen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "documentation",
  },

  // ============================================================
  // BACKUP SETTINGS
  // ============================================================
  {
    key: "backup_enabled",
    category: "backup",
    type: "boolean",
    label: "Backup aktiviert",
    description: "Automatische System-Backups",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "general",
  },
  {
    key: "backup_frequency",
    category: "backup",
    type: "select",
    label: "Backup-Frequenz",
    description: "Wie oft werden Backups erstellt",
    defaultValue: "daily",
    required: true,
    sensitive: false,
    validation: {
      options: ["hourly", "daily", "weekly"],
    },
    group: "schedule",
  },
  {
    key: "backup_retention_count",
    category: "backup",
    type: "number",
    label: "Backup-Aufbewahrung (Anzahl)",
    description: "Wie viele Backups werden aufbewahrt",
    defaultValue: 7,
    required: true,
    sensitive: false,
    validation: {
      min: 1,
      max: 365,
    },
    group: "retention",
  },
  {
    key: "backup_compression",
    category: "backup",
    type: "boolean",
    label: "Backup Komprimierung",
    description: "Backups komprimieren (spart Speicherplatz)",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "options",
  },
  {
    key: "backup_encryption",
    category: "backup",
    type: "boolean",
    label: "Backup Verschlüsselung",
    description: "Backups verschlüsseln (erhöht Sicherheit)",
    defaultValue: false,
    required: true,
    sensitive: false,
    group: "options",
  },

  // ============================================================
  // FEATURE FLAGS
  // ============================================================
  {
    key: "feature_ai_annotator",
    category: "system",
    type: "boolean",
    label: "AI Annotator",
    description: "KI-gestützter Annotator für Dateneingabe",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
  {
    key: "feature_batch_processing",
    category: "system",
    type: "boolean",
    label: "Batch Processing",
    description: "Massenverarbeitung von Datensätzen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
  {
    key: "feature_realtime_updates",
    category: "system",
    type: "boolean",
    label: "Realtime Updates",
    description: "Live-Aktualisierung via WebSocket",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
  {
    key: "feature_advanced_filters",
    category: "system",
    type: "boolean",
    label: "Erweiterte Filter",
    description: "Komplexe Filteroptionen in Listen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
  {
    key: "feature_export_excel",
    category: "system",
    type: "boolean",
    label: "Excel Export",
    description: "Export von Daten als Excel-Datei",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
  {
    key: "feature_export_pdf",
    category: "system",
    type: "boolean",
    label: "PDF Export",
    description: "Export von Berichten als PDF",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
  {
    key: "feature_audit_log",
    category: "system",
    type: "boolean",
    label: "Audit Log",
    description: "Vollständige Protokollierung aller Änderungen",
    defaultValue: true,
    required: true,
    sensitive: false,
    group: "features",
  },
];
